### ISSUE TITLE
Address of operator doesn't change value when you reassign a string

### ISSUE THREAD

**Issue by Thraka** [neilsf/XC-BASIC#117]
When I reassign a string variable to a new location with `let testString$ = testString$ + 1` the string pointer is correct and prints one less character, but the `@testString$` operator continues to report the same memory address. I'm assuming that this happens because the string memory was allocated during the compile and then any `@` was replaced with the memory position. How would you work around this?

```basic
let testString$ = "test str"
let i! = strlen!(testString$)

repeat

    print @testString$
    print testString$
    let testString$ = testString$ + 1

    dec i!

until i! = 0
```

![image](https://user-images.githubusercontent.com/67293991/90290954-ab7cc280-de33-11ea-8b44-6edd4d1c34d1.png)

**Comment by neilsf** [comment]
Him In your example, the variable `testString$` is a string pointer. It is barely an integer that holds the address of the actual string. Thus `@testString$` will not give you the address of the string but the address of the pointer, that is a constant integer. To get the address of the string, try `DEEK(@testString$)`

**Comment by neilsf** [comment]
or better and faster `CAST(@testString$)`

**Comment by Thraka** [comment]
Indeed! Thanks!
