### ISSUE TITLE
Changing text color with CHARAT and/or TEXTAT

### ISSUE THREAD

**Issue by frenchfaso** [neilsf/XC-BASIC#123]
Hello,
is it somehow possible to change the text-color via CHARAT and/or TEXTAT?
Or should I POKE the color ram directly?
Thanks as always!

**Comment by neilsf** [comment]
Not possible as of the current version. See #113

**Comment by frenchfaso** [comment]
My bad!
I commented on the very same issue!
Must have been too excited about the right-aligned numbers! :-p
Thanks :-)
