### ISSUE TITLE
Strange artifact displayed after INPUT

### ISSUE THREAD

**Issue by Diduz** [neilsf/XC-BASIC#132]
Hello, first of all I'd like to thank you for creating this powerful tool. I think it's way more versatile, fast and powerful than the plain Basic V.2.0 a newbie like me would be stuck to. So, thanks again. A lot.
I'm encountering a strange bug: a weird character is shown on screen after the program gets user's INPUT. I don't know if I'm doing something wrong. I attach a screenshot of this problem, the character is underlined in red. Here is the code behind the screenshot (I'm trying to code a text adventure, so INPUT is the core of the experience! :-) ).
I'm using the latest XC=Basic version, i.e. 2.3.09
Thanks.
Dom (Italy)

dim ibuffer![41]
i$ = @ibuffer!
print "{CLR}"
print ""
print "write something here:" ;
input i$, 41
print "" : print ""
print "you wrote:", i$
[
![vice-screen-20210118120755790793](https://user-images.githubusercontent.com/39902698/104908786-3f286100-5987-11eb-9cdc-aabb81499ca5.png)
](url)

**Comment by neilsf** [comment]
Hi Dom
Thanks for giving XC=BASIC a try!
Well, yes, this is a known bug. I'll try to fix it and let you know when it's done.

**Comment by neilsf** [comment]
Had some time after lunch so I fixed it: https://github.com/neilsf/XC-BASIC/releases/tag/v2.3.10
BTW, there is a possible mistake in your code. The buffer should be one byte longer than the maximum string length. This is because one byte must be preserved for the end character, which is a zero byte (0x00). So if buffer is 41 bytes long, the input should be maximum 40 chars.

**Comment by Diduz** [comment]
> Had some time after lunch so I fixed it: https://github.com/neilsf/XC-BASIC/releases/tag/v2.3.10
> BTW, there is a possible mistake in your code. The buffer should be one byte longer than the maximum string length. This is because one byte must be preserved for the end character, which is a zero byte (0x00). So if buffer is 41 bytes long, the input should be maximum 40 chars.

Thank you so much, the mischievous character has disappeared! :-D
I also fixed the buffer mistake. ;-)
