### ISSUE TITLE
Documentation site is offline

### ISSUE THREAD

**Issue by neozeed** [neilsf/XC-BASIC#134]
https://xc-basic.net/doku.php

```
Forbidden
You don't have permission to access this resource.

Apache/2.4.29 (Ubuntu) Server at xc-basic.net Port 443
```

**Comment by neilsf** [comment]
Hi. Thanks for reporting. It must have been a temporary problem and it seems to be working now.

**Comment by neozeed** [comment]
I had to connect to a proxy out side of Hong Kong and it loaded... I guess it's blocking SE Asia?

**Comment by neilsf** [comment]
Oh yes. There were continous bot attacks from the region and the only solution that actually worked was geo ip blocking.

**Comment by neozeed** [comment]
bummer.  I don't know if you can change the 403 to some message about saying proxy elsewhere to hit it, or some 'challenge' thing like how cloudflare does it? 

anyways glad it's not dead!

**Comment by neilsf** [comment]
Yes, a challenge is a cool idea, thanks!
