### ISSUE TITLE
PRG files contain a bad start address

### ISSUE THREAD

**Issue by johanberntsson** [neilsf/XC-BASIC#138]
The two first bytes of the generated PRG files are not 00 08, telling the C64 that the file should be loaded at $0800 when loading with ,8,1. This is incorrect and should be $0801. This creates problems when trying it on the new MEGA65 emulator xemu-xmega65, which checks these bytes to detect if the PRG file is generated for its C64 or C65 mode. Please change so that $0801 is used.

**Comment by neilsf** [comment]
Please try the latest release: https://github.com/neilsf/XC-BASIC/releases/tag/v2.3.12

**Comment by johanberntsson** [comment]
Excellent, the new release solves the problem and everything looks fine. You can close this issue
