### ISSUE TITLE
Sprite multiplexing example

### ISSUE THREAD

**Issue by frenchfaso** [neilsf/XC-BASIC#141]
Hy there,
I've coded a little sprite multiplexing example with the aid of the sprite and rasterinterrupt extensions.
What would be the best way to push it?
Should I do a PR on the sprite extension repo?

![sprite-mplex](https://user-images.githubusercontent.com/1913203/139818808-adc6a5e2-7394-4630-a100-56e217270e4d.gif)

**Comment by neilsf** [comment]
It looks cool, thanks! Maybe you can add it to both Sprite and Interrupts repo?

**Comment by frenchfaso** [comment]
Sure!
Perhaps I should add it first to one repo so that you can check if I have done some gross coding mistakes :grin:

**Comment by neilsf** [comment]
Sure :-)
