### ISSUE TITLE
Crash when running in C64

### ISSUE THREAD

**Issue by orlof** [neilsf/XC-BASIC#144]
c64 consistently crashes when executing this code (I tried to isolate the problem into small snippet):

```
DIM i AS INT

SUB calc_mod(s0 AS INT, s1 AS INT) STATIC
    i = s0 MOD s1
END SUB

CALL calc_mod(0, 255)
```

**Comment by orlof** [comment]
I don't know if this is related but MOD operator seems to return 0 if divisor is greater than 255. e.g.

```
FOR t AS INT = 250 to 260
    print t MOD 256
NEXT
```
prints all zeros.

**Comment by orlof** [comment]
Sorry, submitted to wrong project - I just realised there were XC-Basic and xc-basic3

**Comment by neilsf** [comment]
I can move the issue to xcb3
