### ISSUE TITLE
No "complete" message after compile when data is used

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#15]
Currently I'm trying to port one of my source codes to XC-BASIC. In the original code I have  two lines which look like this:

```
4000 data1,2,40,80,-1,-2,-40,-80
4001 data 32,66,64,125,64,109,64,113,66,66,110,115,112,107,114,91
```

They are read into 3 arrays: d1 and d2 each with a size of 4 and g with a size of 16, which are read on startup of my original BASIC program.

If I understood XC-BASIC correctly I rewrote this code into

```
data d1[] = 1, 2, 40, 80
data d2[] = -1, -2, -40, -80
data g[] = 32, 66, 64, 125, 64, 109, 64, 113, 66, 66, 110, 115, 112, 107, 114, 91
```

But my code doesn't compile anymore. xcb.bat returns without any message and no output file is generated. With removed data lines the code compiles correctly.

I even added a fake test array to the working snake.bas, but had the same result.

**Comment by neilsf** [comment]
Thanks for submitting a bug report!

I can confirm that you're using the DATA statement correctly and this was a bug.

I've added a hotfix to the latest version, please download the latest binary and try to compile again.

**Comment by oliverhermanni** [comment]
Thanks, I'll test it later tonight! Can't wait to convert my Ludum Dare entry Maze of Death to XC-BASIC. :)

**Comment by neilsf** [comment]
Haha, cool title! When you're done, I'll be happy to include it in the examples folder of XC-BASIC if you send it to me (or submit a PR).

Please submit more bug reports if you run into an issue again. It is very useful for me to receive community feedback. Thanks.

**Comment by oliverhermanni** [comment]
Works now, thanks!
