### ISSUE TITLE
Multiline DATA statements

### ISSUE THREAD

**Issue by neilsf** [neilsf/XC-BASIC#29]
A DATA statement should allow items in multiple lines. This possibly requires to introduce a "line concatenation" character, so that the parser will not recognize \n as a a newline, e. g:

    DATA x[] = 1, 2, 3, 4, 5, ~
               6, 7, 8, 9, 10, ~
               11, 12, 13, 14, 15

Tilde (~) is the line concatenation character in this example.

**Comment by oliverhermanni** [comment]
That looks good for me

**Comment by neilsf** [comment]
Merged into latest master branch.
