### ISSUE TITLE
Suggestion: New functions to set/clear IRQ flag

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#35]
I'd like to suggest two new functions: IRQSET and IRQCLEAR as equivalents to SEI and CLI.

**Comment by neilsf** [comment]
A more generic solution will be to support ASM ... ENDASM blocks where you can write anything that is not possible in BASIC.

**Comment by oliverhermanni** [comment]
Yeah, that too.

**Comment by neilsf** [comment]
Inline assembly is now supported. A release is coming soon!
