### ISSUE TITLE
Example needed: change character set

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#36]
I still don't understand how to change a character set in XC-BASIC. Is this possible in XC-BASICs current state?

**Comment by neilsf** [comment]
It is indeed possible. I have added a small example. The charset is saved to a disk image and the program loads it to memory location $3800.

It would be however much better to be able switch the VIC bank to somewhere higher in memory to have more space for the BASIC program. This is yet not supported, but I think it will be relatively easy to do.

**Comment by oliverhermanni** [comment]
Uh, that's it? Thanks!

**Comment by neilsf** [comment]
Yeah, but I'm still concerned with memory. I think I'll also add the option to relocate the library and code somewhere else. For example you'll be able to start your program from let's say $4000 and then you can start your chars, sprites, etc right after the BASIC loader (near $080d).
