### ISSUE TITLE
Cosmetics: Lines in error reports  are off by 1 count

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#39]
Eg. the following line does not report a bug in line 259, col 28, but line 260, col 29

```
Parser error: negLookahead!(wrapAround!(XCBASIC.Spacing, any, XCBASIC.Spacing)) failure at line 259, col 28, after "oveplayerx" expected "anything but \"(\"", but got "() : ~\n   "
```

**Comment by neilsf** [comment]
This is a parser failure reported by [Pegged](https://github.com/PhilippeSigaud/Pegged), the library that parses the input file. I can't really do much about it, sorry. Maybe reorganizing the grammar definition would help a little but I don't think it's worth the efforts.
