### ISSUE TITLE
No 'unary -' (negate operator)

### ISSUE THREAD

**Issue by Viza74** [neilsf/XC-BASIC#40]
No big deal, one can always use 0-variable instead, but thats not very elegant. :)

**Comment by neilsf** [comment]
The unary negation was working in a very early version but I decided to drop it and get back to it later. The problem was that the expression "-123" was misinterpreted by the parser as "123 * -1" and thus slowed down the code. I'll try to fix the parser and bring back this feature to v2.

**Comment by neilsf** [comment]
Postponed, sorry.

**Comment by neilsf** [comment]
Implemented in V3
