### ISSUE TITLE
Only partial support for hexadecimal numbers?

### ISSUE THREAD

**Issue by Viza74** [neilsf/XC-BASIC#41]
It seems that XC-BASIC only understand hexadecimal numbers in the 'origin' and save/load commands?... At least if I try to use anywhere else (mainly peek/poke) I got errors.

**Comment by oliverhermanni** [comment]
Hexadecimal and binary numbers are on my wishlist also and I asked Csaba (the main developer) already about them. They will be supported in a later release.

**Comment by Viza74** [comment]
This is mainly strange because of the partial support (in origin and save/load - I guess those commands not even trying to do anything with their parameters just copy to the asm side as strings? I didn't looked into the code).

I would say it would be clearer to either not supporting at all, or supporting anywhere.
I guessed that support is the ultimate goal, I just didn't know if i is implemented yet, and this is a bug, or not implemented at all (and this is a feature request :) ), so I just reported :)

**Comment by neilsf** [comment]
The parser _does_ allow hexas which means that some of the commands may indeed just copy them into the asm - they are considered to be safe if they passed the parser.
It's an undocumented feature yet.
Full hexa support is coming in v2 - hexas will be allowed everywhere. The new docs will also reflect the changes.

**Comment by neilsf** [comment]
This is now implemented in the development version. The v2 docs will contain information about how to use the different kinds of numeric literals (decimal integer, hexa, binary, floating point).
