### ISSUE TITLE
Arithmetic problem with negative numbers

### ISSUE THREAD

**Issue by Viza74** [neilsf/XC-BASIC#42]
Try this:
print -7/10 -> the result is -0
print -7/10+10 -> the result is -246

It seems that if the result is under -1 the given result will be -0 which is somehow = -FF?...

I had to use this workaround to make it work:
(vx can be negative, and if it is under 32 that casues trouble)
    tempspeed = vx/32
    if tempspeed= -256 then tempspeed = 0

**Comment by neilsf** [comment]
Strange, I get a division by zero. Anyway, I'll have to look at this because this is a major failure.

**Comment by neilsf** [comment]
The two's complement algorithm was a little buggy. Fixed now. Thanks for reporting.
