### ISSUE TITLE
PROCs don't support labels

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#44]
Although the documentation states that labels can be global or local following code does not work. During compile it reports "ERROR: Label loopup does not exist in line 76"

```
proc test
    i = 0
loopup:
    inc i
    if i < 8 then goto loopup
endproc
```

**Comment by neilsf** [comment]
This is a major failure, I'll fix ASAP.

**Comment by oliverhermanni** [comment]
Thanks. With that I can improve my grid walking proc even more

**Comment by neilsf** [comment]
Fixed now. Please try again with the latest binary.

**Comment by oliverhermanni** [comment]
Although it's closed: Works fine now. Had another nasty bug in my code, which I had to hunt down, so I couldn't response earlier. ;)
