### ISSUE TITLE
Constants can not be assigned to vars (dev)

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#48]
Following code works fine in master, but fails in dev:

```
const a = 1
b = a
```

Compile results in  `ERROR: Undefined variable: a in file main.bas in line 2`

**Comment by neilsf** [comment]
Thanks for reporting. This was fixed earlier, I think I just forgot to compile the latest version for Windows. I've pushed a fresh binary now, can you please try again? Thanks.

**Comment by neilsf** [comment]
Please ignore my last comment. It's still buggy, even in the latest version.

**Comment by neilsf** [comment]
Fixed now.
