### ISSUE TITLE
Does PEEK return an integer?

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#51]
Whenever I peek something to a byte var, I get a compiler warning like "WARNING: Integer truncated to byte". So I assume PEEK returns an integer?

This also happens with "INC somevar!", but I guess this one can be ignored.

**Comment by neilsf** [comment]
Functions can have multiple return types. As for PEEK, PEEK() returns an integer while PEEK!() returns a byte. If you assign an integer to a byte variable, you'll get warned. This is faster and nő warning will be emitted: var! = peek!(addr)

**Comment by neilsf** [comment]
INC should not emit a warning. I'll check that when I'm back from holiday.

PS. Sorry for the stupid chars it's my phone's autocorrect.

**Comment by oliverhermanni** [comment]
Thanks for the info about PEEK.

You can ignore the INC. I misinterpreted the output of the compiler.
