### ISSUE TITLE
Why are bytes 0 to 255 and integers -32678 to 32767?

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#52]
If I textat a const like SCREENCOL = 55296 the result will be -10240. 

POKE SCREENCOL, 1 will result in a white background at 55296, though.

Is there a reason why integers have negatives and bytes don't?

**Comment by neilsf** [comment]
There's a brief explanation here: https://xc-basic.net/doku.php?id=numeric_literal
However this page should be rewritten to give a more precise explanation.
The same two-byte integer may be regarded as signed or unsigned as well. By default, the library will treat all integers as signed, but some commands, e.g PEEK, POKE, LOAD, SAVE, etc, usually those that deal with memory addresses will treat the same number as unsigned. So for examle if you pass -1 to PEEK, it will understand it as 65535 as they're the same numbers, just treated differently.

**Comment by oliverhermanni** [comment]
Yeah, but that makes things like debugging or calculating memory positions harder.

I try to explain:

I have 2 consts `SCREEN_COL = 55296` and `SCREEN = 1024`. For my game I need to put a sprite at a certain position on a grid, where each grid tile is somewhere between 1024 and 2023. I wrote a function to calculate sprite x/y positions from any memory location of the screen. Basically it works like this:

```
proc get_playerpos_from_screen_location(screen_mem_loc)
    screen_mem_loc = screen_mem_loc - \SCREEN
    \player_one_y = screen_mem_loc / 40
    tmp = \player_one_y * 40
    \player_one_x = (screen_mem_loc - tmp) * 8 + 24
    \player_one_y = \player_one_y * 8 + 50
endproc
```
That works fine. I also wrote a vice versa function. Let's asume that `x=48` and `y=114`:

```
proc get_screen_location_from_player_pos(x, y)
    if peek(53264) = 1 then x = x + 256
    xx! = (x - 24) / 8 : rem xx! = 3 
    yy! = (y - 50) / 8 : rem yy! = 8
    \player_screen_mem = \SCREEN_COL + (yy! * 40) + xx!
endproc
```

That does not work. Result is -10173. If I do `\SCREEN_COL - yy! * 40 + xx!` the result is -10307. If calculated by `\SCREEN_COL + 8 * 40 + 3` it should be -9917 (or 55619).

There is probably another bug in calculation. But if by any way possible unsigned int would be much easier to work with (suggestion: vars without hash are unsigned, vars with hash are signed).

**Comment by neilsf** [comment]
OK, I'll definitely debug this. Introducing a new variable type would be a bit overkill I think, but there could be a command for formatted output, like sprintf in C. Then one could print a number as unsigned if necessary.

**Comment by neilsf** [comment]
I found why it's working weird though I'm not sure this is a bug. The calculation without the parentheses works fine:

    print \SCREEN_COL + yy! * 40 + xx!
    rem  result: -9917

However with parentheses it does not work as you'd first expect:

    print \SCREEN_COL + (yy! * 40) + xx!
    rem result: -10173

And the reason is that the expression inside the parentheses is of a byte type (yy! and 40 are both bytes). This is evaluated first (it overflows: 8*40 equals 320, it can't fit into a byte) and then it's promoted to an integer. I THINK this is not a bug but I'll double check.

To solve you can do this:

    print \SCREEN_COL + (cast(yy!) * 40) + xx!
    rem  result: -9917

**Comment by neilsf** [comment]
I can confirm this is a bug. If a parenthesized expression is expected to be of integer type then each member of that expression should be promoted to an integer.

**Comment by oliverhermanni** [comment]
Ah, of course! Then it's clear, why it worked earlier. There weren't any byte vars. ;) Thanks! I check it out.

**Comment by neilsf** [comment]
I have extended the documentation with a little explanation:

https://xc-basic.net/doku.php?id=variables#implicit_conversion
