### ISSUE TITLE
Implement WHILE ... ENDWHILE

### ISSUE THREAD

**Issue by neilsf** [neilsf/XC-BASIC#54]
.. optionally REPEAT ... UNTIL

**Comment by neilsf** [comment]
Some thoughts on this. Both `IF` AND `WHILE` should support single line and multi line syntax. This has been a long-time pending feature request. Examples:

  IF <condition> THEN <statements>
  IF <condition> THEN
    <statements>
  ENDIF

  WHILE <condition> <statements> ENDWHILE
  WHILE <condition>
    <statements>
  ENDWHILE

**Comment by neilsf** [comment]
Likewise:

    REPEAT <statements> UNTIL <condition>
    REPEAT
      <statements>
    UNTIL <condition>

**Comment by tomxp411** [comment]
The IF/THEN stuff looks just like QBASIC and VBScript, so it should be comfortable for people used to modern BASIC variants. 

The Single line WHILE should probably require colons. It then becomes identical to a multi line WHILE. 

WHILE X=3 : read x : ENDWHILE

This should make syntax parsing fairly simple.

**Comment by neilsf** [comment]
You're right, WHILE with colons should be working without adding a new grammar rule.

**Comment by neilsf** [comment]
All the above implemented in latest develop (v2.1 candidate).
