### ISSUE TITLE
Semicolon as an alias for REM

### ISSUE THREAD

**Issue by neilsf** [neilsf/XC-BASIC#57]

**Comment by tomxp411** [comment]
Later versions of Microsoft BASIC uses the ‘ (apostrophe) character as a REM substitute, and the semicolon is used in other BASIC commands (specifically in the PRINT statement.)

Wouldn’t it make more sense to use ‘ as a REMark token?

**Comment by neilsf** [comment]
I'd like to use the single quote for character literals in a later version and XC=BASIC doesn't use semicolon in the PRINT statement, that's why I chose the semicolon.

But actually the grammar should be smart enough to recognize whether a character is within an expression or it's the beginning of a statement. So what about using both as aliases for REM?

**Comment by tomxp411** [comment]
I have seen some languages allow the semicolon,  but only if it’s the first character on the line or statement.

**Comment by neilsf** [comment]
Implemented in latest develop branch.
