### ISSUE TITLE
Character literals

### ISSUE THREAD

**Issue by neilsf** [neilsf/XC-BASIC#58]
A character enclosed in single quotes should evaluate to the PETSCII code of that char. Could do the same for screencodes, but I'm unsure about what the syntax should be.

**Comment by tomxp411** [comment]
Suggestion: use the same codes supported by Petcat. CBM PRG Studio and VICE both have some documentation on this. 

Things like {home}, {up}, etc. 

You may also want to support \ as an example character,  \x00 for hex codes. That should cover any reasonable use cases.

**Comment by neilsf** [comment]
Yeah, some of these codes like {home}, {clr} etc.. are already implemented, just the documentation is a little behind.

The hex escape sequence is useful in strings but not very useful in character literals. For example instead of

    x = '\xF0'

you could just use

    x = $F0

as they're equivalent.

**Comment by tomxp411** [comment]
Right. You can just initialize a byte with a byte.  

BasText codes: 
https://github.com/thezerobit/bastext/blob/master/tokens.c

Tok64 codes:
https://github.com/thezerobit/tok64

Those are the two common standards for cross compilers. CBM PRG Studio, arguably the most popular IDE, supports both.

**Comment by neilsf** [comment]
Thanks!
The current implementation is closer to the tok64 syntax but it's possible to add aliases as well, to make it compatible!

**Comment by neilsf** [comment]
Implemented in latest develop.
