### ISSUE TITLE
WAIT only accepts integers

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#69]
`wait 198,1` results in `ERROR: Address must be an integer in file startrader.bas in line 72`

**Comment by neilsf** [comment]
I think there is some mistake here as WAIT never emits this kind of error and implicit type casting works fine. Maybe the error is in another statement?

**Comment by oliverhermanni** [comment]
Oh, maybe I jumped a line!

Then it was POKE 198,0, because before and after the code lines are only PRINTs.

**Comment by neilsf** [comment]
Indeed, POKE doesn't cast implicitly. Again, explicit conversion will do the job.

**Comment by oliverhermanni** [comment]
But POKE should cast implicitly, shouldn't it? Doing `POKE CAST(198), 0` does not look very useful.

**Comment by neilsf** [comment]
I doesn't look nice but does the job. I'll add a fix for implicit casting of course.

**Comment by neilsf** [comment]
Fixed.
