### ISSUE TITLE
INPUT leaves a cursor on screen

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#71]
If the INPUT cursor is visible when pressing `ENTER` the cursor (more like the inverted space) stays on the screen. 

![image](https://user-images.githubusercontent.com/1240179/65336411-9cab7280-dbc6-11e9-8af6-c136471d22f5.png)

**Comment by neilsf** [comment]
I remember this was an issue in an earlier v2.0 version but it has been fixed since then and now I can't reproduce. Can you please post a piece of code? Thanks.

**Comment by neilsf** [comment]
Nevermind, I could reproduce.

**Comment by neilsf** [comment]
Fixed in the upcoming v2.2
