### ISSUE TITLE
XC-BASIC v2.1-rc1 - Compiling error about some variable name

### ISSUE THREAD

**Issue by eagle54** [neilsf/XC-BASIC#72]
hi neilsf,

I am testing xc-basic,

If i want to build the next code i have an error :
`toto = 10`
*** Compile process started ***
Compiling to: C:\C64\XC-BASIC\examples\test\test01.prg

Parser error: negLookahead!(wrapAround!(XCBASIC.Spacing, any, XCBASIC.Spacing)) failure at line 0, col 0, expected "anything but \"t\"", but got "toto = 10\n"

If i test with an other name ex:(titi)
`titi = 10`
It works ok

I think it 's an error when xc-compiler parses toto name (see error parser -> toto <> goto)

otherwise good job, your compiler is promising :+1:

**Comment by neilsf** [comment]
Hi
Thanks for trying XC=BASIC!
`toto` is not a valid identifier because it starts with `to` which is a BASIC keyword. See: https://xc-basic.net/doku.php?id=syntax
I know it's very strict and it may be reconsidered later but this is the rule currently.
