### ISSUE TITLE
Long integers

### ISSUE THREAD

**Issue by neilsf** [neilsf/XC-BASIC#74]
Often you need to deal with large numbers in games: scores, distances, etc.. While floats offer a wide range, they're terribly slow. 16-bit integers are fast, but very limited in range.

XC=BASIC should offer variable type that is a good balance between range and performance. Here are some ideas:

- a large signed integer, possibly 32 bits wide, offering a range from −2,147,483,648 to 2,147,483,647
- an unsigned fixed point decimal, again 32 bits wide, ranging from 0 to 999,999.99 (two decimal places after the radix point)

Please add your thoughts and ideas in the comments.

**Comment by oliverhermanni** [comment]
I think a signed integer is more flexible. In an arcade game bigger scores feel better. In a puzzle game negative scores could be possible (e.g. pushing boxes will lower the score). Fixed point decimals could be "simulated" with string functions.

On the other hand I'd like to have unsigned byte and integer. But you already know that. :P

**Comment by maltekosian** [comment]
I agree with Oliver. Signed integers are a good choice.

**Comment by neilsf** [comment]
Another advantage for the long integer is that they're very easy to convert to/from other integer types.

@oliverhermanni Unsigned integer output is also planned to be implemented in v2.2. No need to introduce a new type for that, as integer arithmetic is the same when signed or unsigned. Only the output formatting decides if it's signed or unsigned.

**Comment by neilsf** [comment]
Another question raises: what sigil to use for the new type? Almost the whole ASCII-table is already reserved :-D I'm thinkink to take away `#` from the integer (as it can be omitted and I strongly believe that no-one actually uses it) and give it to the new type.

**Comment by oliverhermanni** [comment]
Would it be possible to define them by a keyword like other languages do? Eg. `uint`, `int`, etc. Code could look like this:

```
int money = -5000
uint score = 0
```

**Comment by neilsf** [comment]
@oliverhermanni I'd keep the sigil notation for backwards compatibility and as a tribute for the BASIC language.

**Comment by oliverhermanni** [comment]
@neilsf I understand that, but why hold on to something, which might sooner or later become a handicap? Of course sigils need to be kept, e.g. for strings, hexadecimals and binary numbers. But IMHO for decimal numbers they are not intuitive in XC=BASIC. I'm not sure how many times I miss a `!` for a byte. Also if I need to switch from byte to integer in a project I need to search and replace the whole code. 

With new keywords this would be much easier. Adding new number formats would be much easier to add also. Currently I can think of `byte`, `ubyte` (or `ascii` like it's used in PureBasic), `int`, `uint`, `float`, `ufloat`. A number not defined could automatically be defined as integer.

And isn't XC=BASIC itself a tribute to BASIC? ;)

**Comment by neilsf** [comment]
Well I understand your point but it's still a backwards-incompatible change which can be implemented in a later major version.

**Comment by neilsf** [comment]
Let me add another note here. The optimizer's main task is to rewrite the code in such a way that it stores values in registers instead of the stack wherever possible. Now the problem with long integers is that we only have three registers, A, X and Y and therefore they can't be optimized the same way as bytes or short integers.

So I came up with the idea of defining the long integer as 24 bits wide instead of 32 bits. This way the value range is much smaller (−8,388,608 to 8,388,607) but computing speed could be considerably higher.

It's still an open question, no decision have yet been made.

**Comment by oliverhermanni** [comment]
I gueess, that's more than enough.

**Comment by neilsf** [comment]
Well if someone wants to implement a flipper game with crazy scores like 99,999,999 that won't work :-D

But I think 24 bits could be a good trade-off.

**Comment by icepic** [comment]
Flipper games can leave the two last numbers as 00 and let the lowest possible score for anything be 100, and still make you feel like a king with those 99,999,999 points =)

**Comment by neilsf** [comment]
Implemented in V3
