### ISSUE TITLE
Deek() doesn't work in 2.1

### ISSUE THREAD

**Issue by Majikeyric** [neilsf/XC-BASIC#77]
The DeekDoke.bas example doesn't compile.

it returns:

--- Unresolved Symbol List
reserved0              0000 ????         (R )
--- 1 Unresolved symbol

**Comment by neilsf** [comment]
Thanks for reporting! The bug has been fixed. Please download the latest version and try again.

**Comment by Majikeyric** [comment]
Works now, thanks!
