### ISSUE TITLE
Memory information message

### ISSUE THREAD

**Issue by Majikeyric** [neilsf/XC-BASIC#78]
The Data start-end addresses can be reversed if the Data length is short.

example:

Code : ....
Data :  $2aa3 - $2aa2
Variables* .....

**Comment by neilsf** [comment]
Thanks. This is to be fixed with the next release.

**Comment by neilsf** [comment]
Sorry I can't reproduce this. I have tried with different length of data, even with a single byte and it always showed the correct addresses.
