### ISSUE TITLE
Declare variables, arrays with forced address

### ISSUE THREAD

**Issue by Majikeyric** [neilsf/XC-BASIC#79]
Would it be possible to force the start address of a variable or an array when declaring it, at user risks.

dim bgcol! @ $d021
dim charset![2048] @ $2000

maybe it won't be allowed for fast variables

it would allow to manipulate memory locations with array notation instead of Peek & Poke, maybe it is probably faster as well.

**Comment by neilsf** [comment]
This is a valid feature request and relatively easy to implement. Scheduled for v2.2

**Comment by Majikeyric** [comment]
great! thanks!

**Comment by neilsf** [comment]
The new feature has been implemented in the current develop branch. An example code:

    const SCREEN_ADDR = $0400
    dim screen![1000] @ SCREEN_ADDR
    for i=0 to 999
      screen![i] = 65
    next i

**Comment by Majikeyric** [comment]
works well so far :)

**Comment by neilsf** [comment]
I think I'll close this now and we'll get back to it if the pre-release tests fail for v2.2
