### ISSUE TITLE
Change screen address

### ISSUE THREAD

**Issue by Majikeyric** [neilsf/XC-BASIC#80]
Would it be possible to change the screen address to be used with the commands which act on the screen ? (if they use kernal routines maybe it's not possible as $0400 should be hardcoded).

**Comment by neilsf** [comment]
I've been thinking about this for a long time.

1) The easiest way to implement this is through a compiler directive that would instruct the compiler to translate memory locations to the specified VIC bank and a specified screen address within the bank. This would be constant through the program. KERNAL must be notified about the change of course.

2) To allow dynamic switching of the bank and screen address in runtime - that's a harder job and would slow down all related commands. If one wishes to do this, POKE is the only way I'm afraid.

All in all I think we should go for solution #1

**Comment by neilsf** [comment]
I'm closing this for now as this is going to be solved in #82 .
