### ISSUE TITLE
Support for STEP in FOR ... NEXT

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#81]
That would be nice.

**Comment by neilsf** [comment]
Yeah I also think it should be supported for better BASIC compatibility. However, expect significant performance loss when looping with `FOR` with a `STEP` other than 1. Anyway, `FOR` is already pretty slow compared to `REPEAT ... UNTIL`.

Scheduled for v2.3

**Comment by neilsf** [comment]
Done in the upcoming v2.3
