### ISSUE TITLE
Wrong integer range

### ISSUE THREAD

**Issue by Majikeyric** [neilsf/XC-BASIC#83]
In number.d, line 45 the test should be:

"if(num < -32768 || num > 32767) {"

**Comment by neilsf** [comment]
This is a common misunderstanding. Please refer to this page:
https://xc-basic.net/doku.php?id=numeric_literals

Integers can sometimes act unsigned. Some commands (e. g. PEEK and POKE) treat them as unsigned.

**Comment by Majikeyric** [comment]
oupssss... sorry
