### ISSUE TITLE
Support using ZP addresses in POKE and PEEK 

### ISSUE THREAD

**Issue by neilsf** [neilsf/XC-BASIC#89]
Currently CASTing is the only way you can PEEK/POKE from/to a ZP address, e. g:

    print peek(cast(1))

The compiler should allow byte type as address.

**Comment by oliverhermanni** [comment]
Doesn't PEEK!() work here? I had a similar [bug report](https://github.com/neilsf/XC-BASIC/issues/51).

**Comment by neilsf** [comment]
I think that was about the return type of PEEK(). Yes, PEEK() is overloaded for byte and integer return types. That's OK.

However, the address can only be an integer currently, which means it's not intuitive to read/write ZP addresses. A numeric literal under 256 is a byte. The compiler will complain for this.
