### ISSUE TITLE
Reorganize xcbasic64 binaries and scripts

### ISSUE THREAD

**Issue by neilsf** [neilsf/XC-BASIC#93]
Many users are confused about how to install and use XC=BASIC. The following enhancements are necessary:

- remove the `xcb` (or `xcb.bat`) shell scripts and move their functionality to the `xcbasic64` (or `xcbasic64.exe`) executable. The name "xcb" is ambiguous with the "X protocol C-language Binding", anyway.
- Add proper argument parsing and help (e.g `xcbasic64 --help` or `man xcbasic64`)
- Create a self-packaged installer so that users don't have to download files that they don't need. The installer should check if DASM is installed on the system and install it if necessary.

**Comment by oliverhermanni** [comment]
*  Add option to installer for installing XC=Edit. ;)

**Comment by neilsf** [comment]
I think apps must be able to install their dependencies, not vica versa. In this case XC=EDIT should be able to install XC=BASIC. However, the XC=BASIC installer can _recommend_ to install XC=EDIT, which is a good idea.

Another option is to release a bundle that installs both and sets up the correct executable path in XC=EDIT config.

**Comment by neilsf** [comment]
Done in the upcoming v2.3
